server:
  port: 8080
  servlet:
    context-path: /trinity

client:
  id: ccloud-springboot-client-92f235ac-a6e6-48f2-a0d8-a60d6bffe0c2

spring:
  application:
    name: trinity
  kafka:
    bootstrap-servers: pkc-p11xm.us-east-1.aws.confluent.cloud:9092
    topic:
      msk-topic: msk-topic
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="KA6UMHGVOAVWB52M"
        password="DhKEO7BHQLN2lktD3eQwZMYRS6fKjXS0Dbu+7OCmwmNolIAwU4fCFKPXkDrBw9TH";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info