server:
  port: 8080
  servlet:
    context-path: /trinity

spring:
  application:
    name: trinity
  kafka:
    replicas: 2
    partitions: 10
    bootstrap-servers: b-1.studiotrekkafkadev.opvmnn.c25.kafka.us-east-1.amazonaws.com, b-2.studiotrekkafkadev.opvmnn.c25.kafka.us-east-1.amazonaws.com
    topic:
      msk-topic: msk-topic
    producer:
      max-block-ms: 5000
      auto-create-topics: true
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info