server:
  servlet:
    context-path: /trinity

spring:
  application:
    name: trinity

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info