name: trinity

on:
  push:
    branches: [ feature/aws ]

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      STAGE: develop
      SERVICE_NAME: trinity

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Login no ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Extrair versão do pom.xml
        id: version
        run: |
          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" framework/pom.xml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build da imagem com tags latest e versão
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest \
                       -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.version.outputs.version }} .

      - name: Push para o ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.version.outputs.version }}

#      - name: Criar nova task definition com nova imagem
#        id: task-def
#        run: |
#          IMAGE_URI=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.version.outputs.version }}
#
#          # Recupera a task definition base
#          aws ecs describe-task-definition \
#            --task-definition studio-trek-task-dev \
#            --query "taskDefinition" > task-definition.json
#
#          # Atualiza a imagem do primeiro container
#          jq ".containerDefinitions[0].image = \"${IMAGE_URI}\"" task-definition.json > task-def-updated.json
#
#          # Remove campos imutáveis
#          jq "del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)" task-def-updated.json > final-task-def.json
#
#          # Registra nova task definition
#          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
#            --cli-input-json file://final-task-def.json \
#            --query "taskDefinition.taskDefinitionArn" \
#            --output text)
#
#          echo "task_def_arn=$NEW_TASK_DEF_ARN" >> $GITHUB_OUTPUT
#
#      - name: Atualizar serviço ECS
#        run: |
#          aws ecs update-service \
#            --cluster studio-trek-cluster-dev \
#            --service studio-trek-service-dev \
#            --task-definition ${{ steps.task-def.outputs.task_def_arn }} \
#            --force-new-deployment