name: trinity

on:
  push:
    branches: [ feature/aws ]

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      STAGE: develop
      SERVICE_NAME: trinity

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace environment variables in template
        run: |
          sed -i "s|!Ref AmbAwsRegion|${{ secrets.DEV_AWS_REGION }}|g" template.yaml
          sed -i "s|!Ref accessKey|${{ secrets.DEV_AWS_ACCESS_KEY_ID }}|g" template.yaml
          sed -i "s|!Ref secretKey|${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}|g" template.yaml

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extrair versão do pom.xml
        id: version
        run: |
          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" framework/pom.xml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build da imagem com tags latest e versão
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest \
                       -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.version.outputs.version }} .

      - name: Push para o ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.version.outputs.version }}